def func_fail():
    return "fail"
